name: build

on:
  push:
    branches:
    - main

jobs:
  test:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Flutter
        uses: actions/cache@v2
        env:
          cache-name: cache-flutter
        with:
          # Flutter cache files are stored in `~/.flutter` on Linux/macOS
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Install flutter
        uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: '2.10.3'
          channel: 'stable'

      - name: Get platform interface dependencies
        run: flutter pub get
        working-directory: local_image_provider_platform_interface

      - name: Run platform interface tests
        run: flutter test
        working-directory: local_image_provider_platform_interface

      - name: Get plugin dependencies
        run: flutter pub get
        working-directory: local_image_provider

      - name: Run plugin tests
        run: flutter test
        working-directory: local_image_provider
